### ISSUE TITLE
apache3 building list of drives

### ISSUE THREAD

**Issue by Zombar3** [20excal07/RB2TrackPackV1V2#1]
Hi. Apache 3 freeze on building list of drives and and it's all. How to fix it?
P.S. I am on windows 10.

**Comment by 20excal07** [comment]
> Hi. Apache 3 freeze on building list of drives and and it's all. How to fix it? P.S. I am on windows 10.

Hello, I just saw this. I can't really help you on Windows 10, since the software themselves are super old and there haven't really been new versions made that's more tailored for modern Windows (read: they're not mine). My advice to you is to do this on a VM with Windows 7 installed, things should work more smootly there.
