### ISSUE TITLE
Original tracks from RB2

### ISSUE THREAD

**Issue by Zombar3** [20excal07/RB2TrackPackV1V2#2]
Man you're awesome. Is it possible to keep the original tracks from RB2 with TP1 and 2?
Are you planning RB1 and Metal pack?

**Comment by 20excal07** [comment]
**1:** No it isn't possible. RB2 is a dual-layer disc game, recompiling the songs to a dual-layer ISO is not supported by the tools I was working with. You *need* dual-layer to fit all of the songs from RB2 to begin with. That's why I removed them so the track pack songs could just fit into a standard ISO image that you can burn (or put on a USB drive) to play on a softmodded PS2.

**2:** No.

**Comment by Zombar3** [comment]
no need to write to disks, you can create a single-layer image larger than 4GB for HDD with OPL.

**Comment by 20excal07** [comment]
The problem isn't the part where you can write larger than 4GB, it's how the files are structured between the two layers, because the game actually does expect files to be on the second layer once it's over the 4GB limit. Continuing to write on the first layer like that will just crash the game once you try to load songs that are supposed to sit on the second layer. The tools I'm working with doesn't allow me to write files to the second layer, so I'm effectively limited to the 4GB limit whether I like it or not. This is why I had to delete the on-disc songs to begin with. I can't fit the track packs in otherwise.

Believe me, if it was possible to include the track packs *with* the on-disc songs, I would've done it. Actually, I did try that before all this (i.e. write everything to the first layer), and it just isn't possible. Feel free to prove me wrong, though.

(EDIT: the actual limit is more like ~5 GB. anything more needs to be on layer two, so track packs V1+V2 is already a very tight squeeze with only a single layer.)
